version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.1-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: manhnt33/rasa_chatbot:actions
    ports: 
      - 5055:5055
